# Generated by Django 4.0.4 on 2022-05-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautilux_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='francais : quantité', null=True, verbose_name='equipment quantity'),
        ),
    ]
